### ISSUE TITLE
Need more examples in the SYNOPSIS of main module

### ISSUE THREAD

**Issue by zoffixznet** [plu/Pithub#188]
It took me browsing through a ton of modules, writing a semi-negative review, then accidentally stumbling on Pithub::Base (and deleting the review) before I realized that I actually do NOT have to set user/repo on each submodule and that there is a `token` attribute that takes an OAuth token.

I think even if the [Pithub](https://metacpan.org/pod/Pithub)'s synopsis had this extra bit of sample code, it'd save users a lot of confusion and frustration:
```perl
my $pit = Pithub->new(
  user  => $user,
  repo  => $repo,
  token => $oauth_token,
);

$pit->repos->get;
$pit->repos->commits->list;
```

P.S.: it'd also be interesting to know why the dist is called "Pithub". Perhaps an `ABOUT` section in the pod could cover that.

**Comment by oalders** [comment]
We'd accept a pull request for this.  BTW, `Perl + Github = Pithub`.  I initially thought it was `PLU + Github` but @plu set me straight on that point. :)
