### ISSUE TITLE
->pull_requests

### ISSUE THREAD

**Issue by Tux** [plu/Pithub#196]
In order to analyze current status/activity, I want to see the proportion of open PR's to alreade merged PR's. The current interface does not allow me to fetch information about closed PR's.
I'd like to see:

```
my @prs = $ph->repos->get (user => "Tux", repo => "Text-CSV_XS")->pull_requests;
my @prs = $ph->repos->get (user => "Tux", repo => "Text-CSV_XS")->pull_requests ("open"); # same as above
my @prs = $ph->repos->get (user => "Tux", repo => "Text-CSV_XS")->pull_requests ("closed");
my @prs = $ph->repos->get (user => "Tux", repo => "Text-CSV_XS")->pull_requests ("all");
```

**Comment by oalders** [comment]
If I understand you correctly, you're trying to get info on closed pull requests but it's not working?  Could you share your code for that?

**Comment by oalders** [comment]
A `pull_requests` method would be nice to have.
