### ISSUE TITLE
Feature Request: Markdown

### ISSUE THREAD

**Issue by rlove** [plu/Pithub#198]
Requesting the module support the markdown area of the API.

https://developer.github.com/v3/markdown/

**Comment by oalders** [comment]
@rlove are you motivated to put this together?  Patches are being applied, but there hasn't been any work on new features lately.

**Comment by rlove** [comment]
I will take a look at it, since I do need to call this API from Perl.

**Comment by oalders** [comment]
Great!  Let me know if you need anything.

**Comment by rlove** [comment]
We moved away from Perl for our GitHub interactions so I don't have a need for this anymore.

**Comment by jjatria** [comment]
How does this look for an initial implementation?

https://github.com/plu/Pithub/compare/master...jjatria:feat-markdown

Comments welcome. 🎉

**Comment by oalders** [comment]
@jjatria looks good!  Could you turn that into a pull request?
