### ISSUE TITLE
Feature: method to query rate_limit

### ISSUE THREAD

**Issue by jjatria** [plu/Pithub#202]
Pithub does not currently have a method to query the current API rate_limit for the authentication method in use.

A `rate_limit` method could be added to `Pithub::Base` that used `request` method to call the rate limit endpoint. This would enable any Pithub object to get information on the rate limit for whatever authentication method was active for that object.

An initial implementation of this feature is already in place in [a local branch](https://github.com/plu/Pithub/compare/master...jjatria:feat-rate-limit). If this seems OK, I'd be happy to submit a PR for this to be added.

**Comment by oalders** [comment]
Looks good!
