### ISSUE TITLE
Drop dependency on Array::Iterator

### ISSUE THREAD

**Issue by Tux** [plu/Pithub#221]
Pithub depends on Array::Iterator used (only) in lib/Pithub/Result.pm as _iterator for next and _build_iterator

Array::Iterator is up for adoption according to its CPAN content

Array::Iterator is currently by PERLANCAR, which I have blocked as I do not want every perl/CPAN functionality duplicated in my installation (nothing to do with quality or trust). His dependency chains are insane and mostly depend on their own modules/releases.
This makes this issue in essention *my* issue, and not an issue of this module, but still. I am free to do this request :)

I've converted Array::Iterator into Pithub::ResultSet in https://tux.nl/Files/Pithub-0.01038.tgz - feel free to use that verbatim (though I guess you want to restyle/reformat `lib/Pithub/ResultSet.pm` as that is in my style now

**Comment by oalders** [comment]
Hi @Tux!

Are you able to submit this as a pull request? That would be easier to review. 😀

**Comment by oalders** [comment]
Closed via #222
