### ISSUE TITLE
Github requires boolean values for true/false values not 0/1

### ISSUE THREAD

**Issue by timlegge** [plu/Pithub#231]
https://github.com/plu/Pithub/blob/cd85ed31181c5dc6df14f97852de894c1d2a790b/lib/Pithub/Repos/Releases.pm#L113

I had errors attempting to create a release when using 0 or 1 for the true false values as documented.

I have to do the following:

```
use constant false => \0;
sub true () { return \1 } # note the empty prototype

```
Then I had to use 'true' or 'false' for the attributes that required boolean values.

**Comment by oalders** [comment]
Hi @timlegge. Which version of Perl are you seeing this on?

**Comment by timlegge** [comment]
I believe it's 5.36 using Perl Brew. I will post the details a little later
this morning.

**Comment by timlegge** [comment]
@oalders Here are the details:

Summary of my perl5 (revision 5 version 36 subversion 1) configuration:
   
  Platform:
    osname=linux
    osvers=5.15.0-76-generic
    archname=x86_64-linux-thread-multi
    uname='linux vivobook 5.15.0-76-generic #83-ubuntu smp thu jun 15 19:16:32 utc 2023 x86_64 x86_64 x86_64 gnulinux '
    config_args='-de -Dprefix=/home/tim/perl5/perlbrew/perls/perl-5.36.1 -Dusemultiplicity -Dusethreads -Aeval:scriptdir=/home/tim/perl5/perlbrew/perls/perl-5.36.1/bin'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.3.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/x86_64-linux-gnu/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.35'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Jul 11 2023 22:13:47
  %ENV:
    PERLBREW_HOME="/home/tim/.perlbrew"
    PERLBREW_MANPATH="/home/tim/perl5/perlbrew/perls/perl-5.36.1/man"
    PERLBREW_PATH="/home/tim/perl5/perlbrew/bin:/home/tim/perl5/perlbrew/perls/perl-5.36.1/bin"
    PERLBREW_PERL="perl-5.36.1"
    PERLBREW_ROOT="/home/tim/perl5/perlbrew"
    PERLBREW_SHELLRC_VERSION="0.96"
    PERLBREW_VERSION="0.96"
  @INC:
    /home/tim/perl5/perlbrew/perls/perl-5.36.1/lib/site_perl/5.36.1/x86_64-linux-thread-multi
    /home/tim/perl5/perlbrew/perls/perl-5.36.1/lib/site_perl/5.36.1
    /home/tim/perl5/perlbrew/perls/perl-5.36.1/lib/5.36.1/x86_64-linux-thread-multi
    /home/tim/perl5/perlbrew/perls/perl-5.36.1/lib/5.36.1
